# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Grille.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(850, 783)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 10, 201, 171))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.status = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.status.setObjectName(_fromUtf8("status"))
        self.PAUSE = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PAUSE.setObjectName(_fromUtf8("PAUSE"))
        self.status.addWidget(self.PAUSE)
        self.PLAY = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PLAY.setObjectName(_fromUtf8("PLAY"))
        self.status.addWidget(self.PLAY)
        self.QUIT = QtGui.QPushButton(self.verticalLayoutWidget)
        self.QUIT.setObjectName(_fromUtf8("QUIT"))
        self.status.addWidget(self.QUIT)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Pseudo = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.Pseudo.setObjectName(_fromUtf8("Pseudo"))
        self.horizontalLayout_2.addWidget(self.Pseudo)
        self.status.addLayout(self.horizontalLayout_2)
        self.PSEUDO = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PSEUDO.setObjectName(_fromUtf8("PSEUDO"))
        self.status.addWidget(self.PSEUDO)
        self.moveUp = QtGui.QToolButton(self.centralwidget)
        self.moveUp.setGeometry(QtCore.QRect(720, 630, 41, 41))
        self.moveUp.setObjectName(_fromUtf8("moveUp"))
        self.moveLeft = QtGui.QToolButton(self.centralwidget)
        self.moveLeft.setGeometry(QtCore.QRect(680, 670, 41, 41))
        self.moveLeft.setObjectName(_fromUtf8("moveLeft"))
        self.moveRight = QtGui.QToolButton(self.centralwidget)
        self.moveRight.setGeometry(QtCore.QRect(760, 670, 41, 41))
        self.moveRight.setObjectName(_fromUtf8("moveRight"))
        self.moveDown = QtGui.QToolButton(self.centralwidget)
        self.moveDown.setGeometry(QtCore.QRect(720, 710, 41, 41))
        self.moveDown.setObjectName(_fromUtf8("moveDown"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 51, 51))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gril_9_0 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gril_9_0.setObjectName(_fromUtf8("gril_9_0"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 51, 51))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gril_8_0 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gril_8_0.setObjectName(_fromUtf8("gril_8_0"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 130, 51, 51))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gril_7_0 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gril_7_0.setObjectName(_fromUtf8("gril_7_0"))
        self.gridLayoutWidget_11 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(30, 190, 51, 51))
        self.gridLayoutWidget_11.setObjectName(_fromUtf8("gridLayoutWidget_11"))
        self.gril_6_0 = QtGui.QGridLayout(self.gridLayoutWidget_11)
        self.gril_6_0.setObjectName(_fromUtf8("gril_6_0"))
        self.gridLayoutWidget_12 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(30, 250, 51, 51))
        self.gridLayoutWidget_12.setObjectName(_fromUtf8("gridLayoutWidget_12"))
        self.gril_5_0 = QtGui.QGridLayout(self.gridLayoutWidget_12)
        self.gril_5_0.setObjectName(_fromUtf8("gril_5_0"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 310, 51, 51))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gril_4_0 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gril_4_0.setObjectName(_fromUtf8("gril_4_0"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(30, 370, 51, 51))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gril_3_0 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gril_3_0.setObjectName(_fromUtf8("gril_3_0"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 430, 51, 51))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gril_2_0 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gril_2_0.setObjectName(_fromUtf8("gril_2_0"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(30, 490, 51, 51))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gril_1_0 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gril_1_0.setObjectName(_fromUtf8("gril_1_0"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(30, 550, 51, 51))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gril_0_0 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gril_0_0.setObjectName(_fromUtf8("gril_0_0"))
        self.gridLayoutWidget_10 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(90, 430, 51, 51))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gril_2_1 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gril_2_1.setObjectName(_fromUtf8("gril_2_1"))
        self.gridLayoutWidget_13 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(90, 190, 51, 51))
        self.gridLayoutWidget_13.setObjectName(_fromUtf8("gridLayoutWidget_13"))
        self.gril_6_1 = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.gril_6_1.setObjectName(_fromUtf8("gril_6_1"))
        self.gridLayoutWidget_14 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(90, 490, 51, 51))
        self.gridLayoutWidget_14.setObjectName(_fromUtf8("gridLayoutWidget_14"))
        self.gril_1_1 = QtGui.QGridLayout(self.gridLayoutWidget_14)
        self.gril_1_1.setObjectName(_fromUtf8("gril_1_1"))
        self.gridLayoutWidget_15 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(90, 550, 51, 51))
        self.gridLayoutWidget_15.setObjectName(_fromUtf8("gridLayoutWidget_15"))
        self.gril_0_1 = QtGui.QGridLayout(self.gridLayoutWidget_15)
        self.gril_0_1.setObjectName(_fromUtf8("gril_0_1"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(90, 70, 51, 51))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gril_8_1 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gril_8_1.setObjectName(_fromUtf8("gril_8_1"))
        self.gridLayoutWidget_16 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(90, 310, 51, 51))
        self.gridLayoutWidget_16.setObjectName(_fromUtf8("gridLayoutWidget_16"))
        self.gril_4_1 = QtGui.QGridLayout(self.gridLayoutWidget_16)
        self.gril_4_1.setObjectName(_fromUtf8("gril_4_1"))
        self.gridLayoutWidget_17 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(90, 370, 51, 51))
        self.gridLayoutWidget_17.setObjectName(_fromUtf8("gridLayoutWidget_17"))
        self.gril_3_1 = QtGui.QGridLayout(self.gridLayoutWidget_17)
        self.gril_3_1.setObjectName(_fromUtf8("gril_3_1"))
        self.gridLayoutWidget_18 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(90, 130, 51, 51))
        self.gridLayoutWidget_18.setObjectName(_fromUtf8("gridLayoutWidget_18"))
        self.gril_7_1 = QtGui.QGridLayout(self.gridLayoutWidget_18)
        self.gril_7_1.setObjectName(_fromUtf8("gril_7_1"))
        self.gridLayoutWidget_19 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(90, 10, 51, 51))
        self.gridLayoutWidget_19.setObjectName(_fromUtf8("gridLayoutWidget_19"))
        self.gril_9_1 = QtGui.QGridLayout(self.gridLayoutWidget_19)
        self.gril_9_1.setObjectName(_fromUtf8("gril_9_1"))
        self.gridLayoutWidget_20 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(90, 250, 51, 51))
        self.gridLayoutWidget_20.setObjectName(_fromUtf8("gridLayoutWidget_20"))
        self.gril_5_1 = QtGui.QGridLayout(self.gridLayoutWidget_20)
        self.gril_5_1.setObjectName(_fromUtf8("gril_5_1"))
        self.gridLayoutWidget_21 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_21.setGeometry(QtCore.QRect(150, 430, 51, 51))
        self.gridLayoutWidget_21.setObjectName(_fromUtf8("gridLayoutWidget_21"))
        self.gril_2_2 = QtGui.QGridLayout(self.gridLayoutWidget_21)
        self.gril_2_2.setObjectName(_fromUtf8("gril_2_2"))
        self.gridLayoutWidget_22 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_22.setGeometry(QtCore.QRect(150, 190, 51, 51))
        self.gridLayoutWidget_22.setObjectName(_fromUtf8("gridLayoutWidget_22"))
        self.gril_6_2 = QtGui.QGridLayout(self.gridLayoutWidget_22)
        self.gril_6_2.setObjectName(_fromUtf8("gril_6_2"))
        self.gridLayoutWidget_23 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_23.setGeometry(QtCore.QRect(150, 490, 51, 51))
        self.gridLayoutWidget_23.setObjectName(_fromUtf8("gridLayoutWidget_23"))
        self.gril_1_2 = QtGui.QGridLayout(self.gridLayoutWidget_23)
        self.gril_1_2.setObjectName(_fromUtf8("gril_1_2"))
        self.gridLayoutWidget_24 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_24.setGeometry(QtCore.QRect(150, 550, 51, 51))
        self.gridLayoutWidget_24.setObjectName(_fromUtf8("gridLayoutWidget_24"))
        self.gril_0_2 = QtGui.QGridLayout(self.gridLayoutWidget_24)
        self.gril_0_2.setObjectName(_fromUtf8("gril_0_2"))
        self.gridLayoutWidget_25 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_25.setGeometry(QtCore.QRect(150, 70, 51, 51))
        self.gridLayoutWidget_25.setObjectName(_fromUtf8("gridLayoutWidget_25"))
        self.gril_8_2 = QtGui.QGridLayout(self.gridLayoutWidget_25)
        self.gril_8_2.setObjectName(_fromUtf8("gril_8_2"))
        self.gridLayoutWidget_26 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_26.setGeometry(QtCore.QRect(150, 310, 51, 51))
        self.gridLayoutWidget_26.setObjectName(_fromUtf8("gridLayoutWidget_26"))
        self.gril_4_2 = QtGui.QGridLayout(self.gridLayoutWidget_26)
        self.gril_4_2.setObjectName(_fromUtf8("gril_4_2"))
        self.gridLayoutWidget_27 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_27.setGeometry(QtCore.QRect(150, 370, 51, 51))
        self.gridLayoutWidget_27.setObjectName(_fromUtf8("gridLayoutWidget_27"))
        self.gril_3_2 = QtGui.QGridLayout(self.gridLayoutWidget_27)
        self.gril_3_2.setObjectName(_fromUtf8("gril_3_2"))
        self.gridLayoutWidget_28 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_28.setGeometry(QtCore.QRect(150, 130, 51, 51))
        self.gridLayoutWidget_28.setObjectName(_fromUtf8("gridLayoutWidget_28"))
        self.gril_7_2 = QtGui.QGridLayout(self.gridLayoutWidget_28)
        self.gril_7_2.setObjectName(_fromUtf8("gril_7_2"))
        self.gridLayoutWidget_29 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_29.setGeometry(QtCore.QRect(150, 10, 51, 51))
        self.gridLayoutWidget_29.setObjectName(_fromUtf8("gridLayoutWidget_29"))
        self.gril_9_2 = QtGui.QGridLayout(self.gridLayoutWidget_29)
        self.gril_9_2.setObjectName(_fromUtf8("gril_9_2"))
        self.gridLayoutWidget_30 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_30.setGeometry(QtCore.QRect(150, 250, 51, 51))
        self.gridLayoutWidget_30.setObjectName(_fromUtf8("gridLayoutWidget_30"))
        self.gril_5_3 = QtGui.QGridLayout(self.gridLayoutWidget_30)
        self.gril_5_3.setObjectName(_fromUtf8("gril_5_3"))
        self.gridLayoutWidget_31 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_31.setGeometry(QtCore.QRect(210, 310, 51, 51))
        self.gridLayoutWidget_31.setObjectName(_fromUtf8("gridLayoutWidget_31"))
        self.gril_4_3 = QtGui.QGridLayout(self.gridLayoutWidget_31)
        self.gril_4_3.setObjectName(_fromUtf8("gril_4_3"))
        self.gridLayoutWidget_32 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_32.setGeometry(QtCore.QRect(330, 130, 51, 51))
        self.gridLayoutWidget_32.setObjectName(_fromUtf8("gridLayoutWidget_32"))
        self.gril_7_5 = QtGui.QGridLayout(self.gridLayoutWidget_32)
        self.gril_7_5.setObjectName(_fromUtf8("gril_7_5"))
        self.gridLayoutWidget_33 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_33.setGeometry(QtCore.QRect(210, 190, 51, 51))
        self.gridLayoutWidget_33.setObjectName(_fromUtf8("gridLayoutWidget_33"))
        self.gril_6_3 = QtGui.QGridLayout(self.gridLayoutWidget_33)
        self.gril_6_3.setObjectName(_fromUtf8("gril_6_3"))
        self.gridLayoutWidget_34 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_34.setGeometry(QtCore.QRect(270, 550, 51, 51))
        self.gridLayoutWidget_34.setObjectName(_fromUtf8("gridLayoutWidget_34"))
        self.gril_0_4 = QtGui.QGridLayout(self.gridLayoutWidget_34)
        self.gril_0_4.setObjectName(_fromUtf8("gril_0_4"))
        self.gridLayoutWidget_35 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_35.setGeometry(QtCore.QRect(210, 10, 51, 51))
        self.gridLayoutWidget_35.setObjectName(_fromUtf8("gridLayoutWidget_35"))
        self.gril_9_3 = QtGui.QGridLayout(self.gridLayoutWidget_35)
        self.gril_9_3.setObjectName(_fromUtf8("gril_9_3"))
        self.gridLayoutWidget_36 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_36.setGeometry(QtCore.QRect(270, 430, 51, 51))
        self.gridLayoutWidget_36.setObjectName(_fromUtf8("gridLayoutWidget_36"))
        self.gril_2_4 = QtGui.QGridLayout(self.gridLayoutWidget_36)
        self.gril_2_4.setObjectName(_fromUtf8("gril_2_4"))
        self.gridLayoutWidget_37 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_37.setGeometry(QtCore.QRect(330, 310, 51, 51))
        self.gridLayoutWidget_37.setObjectName(_fromUtf8("gridLayoutWidget_37"))
        self.gril_4_5 = QtGui.QGridLayout(self.gridLayoutWidget_37)
        self.gril_4_5.setObjectName(_fromUtf8("gril_4_5"))
        self.gridLayoutWidget_38 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_38.setGeometry(QtCore.QRect(270, 130, 51, 51))
        self.gridLayoutWidget_38.setObjectName(_fromUtf8("gridLayoutWidget_38"))
        self.gril_7_4 = QtGui.QGridLayout(self.gridLayoutWidget_38)
        self.gril_7_4.setObjectName(_fromUtf8("gril_7_4"))
        self.gridLayoutWidget_39 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_39.setGeometry(QtCore.QRect(270, 190, 51, 51))
        self.gridLayoutWidget_39.setObjectName(_fromUtf8("gridLayoutWidget_39"))
        self.gril_6_4 = QtGui.QGridLayout(self.gridLayoutWidget_39)
        self.gril_6_4.setObjectName(_fromUtf8("gril_6_4"))
        self.gridLayoutWidget_40 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_40.setGeometry(QtCore.QRect(330, 190, 51, 51))
        self.gridLayoutWidget_40.setObjectName(_fromUtf8("gridLayoutWidget_40"))
        self.gril_6_5 = QtGui.QGridLayout(self.gridLayoutWidget_40)
        self.gril_6_5.setObjectName(_fromUtf8("gril_6_5"))
        self.gridLayoutWidget_41 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_41.setGeometry(QtCore.QRect(210, 250, 51, 51))
        self.gridLayoutWidget_41.setObjectName(_fromUtf8("gridLayoutWidget_41"))
        self.gril_5_4 = QtGui.QGridLayout(self.gridLayoutWidget_41)
        self.gril_5_4.setObjectName(_fromUtf8("gril_5_4"))
        self.gridLayoutWidget_42 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_42.setGeometry(QtCore.QRect(270, 370, 51, 51))
        self.gridLayoutWidget_42.setObjectName(_fromUtf8("gridLayoutWidget_42"))
        self.gril_3_4 = QtGui.QGridLayout(self.gridLayoutWidget_42)
        self.gril_3_4.setObjectName(_fromUtf8("gril_3_4"))
        self.gridLayoutWidget_43 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_43.setGeometry(QtCore.QRect(270, 250, 51, 51))
        self.gridLayoutWidget_43.setObjectName(_fromUtf8("gridLayoutWidget_43"))
        self.gril_5_5 = QtGui.QGridLayout(self.gridLayoutWidget_43)
        self.gril_5_5.setObjectName(_fromUtf8("gril_5_5"))
        self.gridLayoutWidget_44 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_44.setGeometry(QtCore.QRect(210, 130, 51, 51))
        self.gridLayoutWidget_44.setObjectName(_fromUtf8("gridLayoutWidget_44"))
        self.gril_7_3 = QtGui.QGridLayout(self.gridLayoutWidget_44)
        self.gril_7_3.setObjectName(_fromUtf8("gril_7_3"))
        self.gridLayoutWidget_45 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_45.setGeometry(QtCore.QRect(330, 370, 51, 51))
        self.gridLayoutWidget_45.setObjectName(_fromUtf8("gridLayoutWidget_45"))
        self.gril_3_5 = QtGui.QGridLayout(self.gridLayoutWidget_45)
        self.gril_3_5.setObjectName(_fromUtf8("gril_3_5"))
        self.gridLayoutWidget_46 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_46.setGeometry(QtCore.QRect(270, 10, 51, 51))
        self.gridLayoutWidget_46.setObjectName(_fromUtf8("gridLayoutWidget_46"))
        self.gril_9_4 = QtGui.QGridLayout(self.gridLayoutWidget_46)
        self.gril_9_4.setObjectName(_fromUtf8("gril_9_4"))
        self.gridLayoutWidget_47 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_47.setGeometry(QtCore.QRect(330, 550, 51, 51))
        self.gridLayoutWidget_47.setObjectName(_fromUtf8("gridLayoutWidget_47"))
        self.gril_0_5 = QtGui.QGridLayout(self.gridLayoutWidget_47)
        self.gril_0_5.setObjectName(_fromUtf8("gril_0_5"))
        self.gridLayoutWidget_48 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_48.setGeometry(QtCore.QRect(330, 250, 51, 51))
        self.gridLayoutWidget_48.setObjectName(_fromUtf8("gridLayoutWidget_48"))
        self.gril_5_6 = QtGui.QGridLayout(self.gridLayoutWidget_48)
        self.gril_5_6.setObjectName(_fromUtf8("gril_5_6"))
        self.gridLayoutWidget_49 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_49.setGeometry(QtCore.QRect(270, 70, 51, 51))
        self.gridLayoutWidget_49.setObjectName(_fromUtf8("gridLayoutWidget_49"))
        self.gril_8_4 = QtGui.QGridLayout(self.gridLayoutWidget_49)
        self.gril_8_4.setObjectName(_fromUtf8("gril_8_4"))
        self.gridLayoutWidget_50 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_50.setGeometry(QtCore.QRect(270, 310, 51, 51))
        self.gridLayoutWidget_50.setObjectName(_fromUtf8("gridLayoutWidget_50"))
        self.gril_4_4 = QtGui.QGridLayout(self.gridLayoutWidget_50)
        self.gril_4_4.setObjectName(_fromUtf8("gril_4_4"))
        self.gridLayoutWidget_51 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_51.setGeometry(QtCore.QRect(330, 10, 51, 51))
        self.gridLayoutWidget_51.setObjectName(_fromUtf8("gridLayoutWidget_51"))
        self.gril_9_5 = QtGui.QGridLayout(self.gridLayoutWidget_51)
        self.gril_9_5.setObjectName(_fromUtf8("gril_9_5"))
        self.gridLayoutWidget_52 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_52.setGeometry(QtCore.QRect(270, 490, 51, 51))
        self.gridLayoutWidget_52.setObjectName(_fromUtf8("gridLayoutWidget_52"))
        self.gril_1_4 = QtGui.QGridLayout(self.gridLayoutWidget_52)
        self.gril_1_4.setObjectName(_fromUtf8("gril_1_4"))
        self.gridLayoutWidget_53 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_53.setGeometry(QtCore.QRect(330, 70, 51, 51))
        self.gridLayoutWidget_53.setObjectName(_fromUtf8("gridLayoutWidget_53"))
        self.gril_8_5 = QtGui.QGridLayout(self.gridLayoutWidget_53)
        self.gril_8_5.setObjectName(_fromUtf8("gril_8_5"))
        self.gridLayoutWidget_54 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_54.setGeometry(QtCore.QRect(210, 430, 51, 51))
        self.gridLayoutWidget_54.setObjectName(_fromUtf8("gridLayoutWidget_54"))
        self.gril_2_3 = QtGui.QGridLayout(self.gridLayoutWidget_54)
        self.gril_2_3.setObjectName(_fromUtf8("gril_2_3"))
        self.gridLayoutWidget_55 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_55.setGeometry(QtCore.QRect(210, 490, 51, 51))
        self.gridLayoutWidget_55.setObjectName(_fromUtf8("gridLayoutWidget_55"))
        self.gril_1_3 = QtGui.QGridLayout(self.gridLayoutWidget_55)
        self.gril_1_3.setObjectName(_fromUtf8("gril_1_3"))
        self.gridLayoutWidget_56 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_56.setGeometry(QtCore.QRect(210, 70, 51, 51))
        self.gridLayoutWidget_56.setObjectName(_fromUtf8("gridLayoutWidget_56"))
        self.gril_8_3 = QtGui.QGridLayout(self.gridLayoutWidget_56)
        self.gril_8_3.setObjectName(_fromUtf8("gril_8_3"))
        self.gridLayoutWidget_57 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_57.setGeometry(QtCore.QRect(330, 490, 51, 51))
        self.gridLayoutWidget_57.setObjectName(_fromUtf8("gridLayoutWidget_57"))
        self.gril_1_5 = QtGui.QGridLayout(self.gridLayoutWidget_57)
        self.gril_1_5.setObjectName(_fromUtf8("gril_1_5"))
        self.gridLayoutWidget_58 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_58.setGeometry(QtCore.QRect(210, 550, 51, 51))
        self.gridLayoutWidget_58.setObjectName(_fromUtf8("gridLayoutWidget_58"))
        self.gril_0_3 = QtGui.QGridLayout(self.gridLayoutWidget_58)
        self.gril_0_3.setObjectName(_fromUtf8("gril_0_3"))
        self.gridLayoutWidget_59 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_59.setGeometry(QtCore.QRect(330, 430, 51, 51))
        self.gridLayoutWidget_59.setObjectName(_fromUtf8("gridLayoutWidget_59"))
        self.gril_2_5 = QtGui.QGridLayout(self.gridLayoutWidget_59)
        self.gril_2_5.setObjectName(_fromUtf8("gril_2_5"))
        self.gridLayoutWidget_60 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_60.setGeometry(QtCore.QRect(210, 370, 51, 51))
        self.gridLayoutWidget_60.setObjectName(_fromUtf8("gridLayoutWidget_60"))
        self.gril_3_3 = QtGui.QGridLayout(self.gridLayoutWidget_60)
        self.gril_3_3.setObjectName(_fromUtf8("gril_3_3"))
        self.gridLayoutWidget_61 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_61.setGeometry(QtCore.QRect(390, 310, 51, 51))
        self.gridLayoutWidget_61.setObjectName(_fromUtf8("gridLayoutWidget_61"))
        self.gril_4_6 = QtGui.QGridLayout(self.gridLayoutWidget_61)
        self.gril_4_6.setObjectName(_fromUtf8("gril_4_6"))
        self.gridLayoutWidget_62 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_62.setGeometry(QtCore.QRect(510, 130, 51, 51))
        self.gridLayoutWidget_62.setObjectName(_fromUtf8("gridLayoutWidget_62"))
        self.gril_7_8 = QtGui.QGridLayout(self.gridLayoutWidget_62)
        self.gril_7_8.setObjectName(_fromUtf8("gril_7_8"))
        self.gridLayoutWidget_63 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_63.setGeometry(QtCore.QRect(390, 190, 51, 51))
        self.gridLayoutWidget_63.setObjectName(_fromUtf8("gridLayoutWidget_63"))
        self.gril_6_6 = QtGui.QGridLayout(self.gridLayoutWidget_63)
        self.gril_6_6.setObjectName(_fromUtf8("gril_6_6"))
        self.gridLayoutWidget_64 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_64.setGeometry(QtCore.QRect(450, 550, 51, 51))
        self.gridLayoutWidget_64.setObjectName(_fromUtf8("gridLayoutWidget_64"))
        self.gril_0_7 = QtGui.QGridLayout(self.gridLayoutWidget_64)
        self.gril_0_7.setObjectName(_fromUtf8("gril_0_7"))
        self.gridLayoutWidget_65 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_65.setGeometry(QtCore.QRect(390, 10, 51, 51))
        self.gridLayoutWidget_65.setObjectName(_fromUtf8("gridLayoutWidget_65"))
        self.gril_9_6 = QtGui.QGridLayout(self.gridLayoutWidget_65)
        self.gril_9_6.setObjectName(_fromUtf8("gril_9_6"))
        self.gridLayoutWidget_66 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_66.setGeometry(QtCore.QRect(450, 430, 51, 51))
        self.gridLayoutWidget_66.setObjectName(_fromUtf8("gridLayoutWidget_66"))
        self.gril_2_7 = QtGui.QGridLayout(self.gridLayoutWidget_66)
        self.gril_2_7.setObjectName(_fromUtf8("gril_2_7"))
        self.gridLayoutWidget_67 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_67.setGeometry(QtCore.QRect(510, 310, 51, 51))
        self.gridLayoutWidget_67.setObjectName(_fromUtf8("gridLayoutWidget_67"))
        self.gril_4_10 = QtGui.QGridLayout(self.gridLayoutWidget_67)
        self.gril_4_10.setObjectName(_fromUtf8("gril_4_10"))
        self.gridLayoutWidget_68 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_68.setGeometry(QtCore.QRect(450, 130, 51, 51))
        self.gridLayoutWidget_68.setObjectName(_fromUtf8("gridLayoutWidget_68"))
        self.gril_7_7 = QtGui.QGridLayout(self.gridLayoutWidget_68)
        self.gril_7_7.setObjectName(_fromUtf8("gril_7_7"))
        self.gridLayoutWidget_69 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_69.setGeometry(QtCore.QRect(450, 190, 51, 51))
        self.gridLayoutWidget_69.setObjectName(_fromUtf8("gridLayoutWidget_69"))
        self.gril_6_7 = QtGui.QGridLayout(self.gridLayoutWidget_69)
        self.gril_6_7.setObjectName(_fromUtf8("gril_6_7"))
        self.gridLayoutWidget_70 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_70.setGeometry(QtCore.QRect(510, 190, 51, 51))
        self.gridLayoutWidget_70.setObjectName(_fromUtf8("gridLayoutWidget_70"))
        self.gril_6_8 = QtGui.QGridLayout(self.gridLayoutWidget_70)
        self.gril_6_8.setObjectName(_fromUtf8("gril_6_8"))
        self.gridLayoutWidget_71 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_71.setGeometry(QtCore.QRect(390, 250, 51, 51))
        self.gridLayoutWidget_71.setObjectName(_fromUtf8("gridLayoutWidget_71"))
        self.gril_5_7 = QtGui.QGridLayout(self.gridLayoutWidget_71)
        self.gril_5_7.setObjectName(_fromUtf8("gril_5_7"))
        self.gridLayoutWidget_72 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_72.setGeometry(QtCore.QRect(450, 370, 51, 51))
        self.gridLayoutWidget_72.setObjectName(_fromUtf8("gridLayoutWidget_72"))
        self.gril_4_7 = QtGui.QGridLayout(self.gridLayoutWidget_72)
        self.gril_4_7.setObjectName(_fromUtf8("gril_4_7"))
        self.gridLayoutWidget_73 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_73.setGeometry(QtCore.QRect(450, 250, 51, 51))
        self.gridLayoutWidget_73.setObjectName(_fromUtf8("gridLayoutWidget_73"))
        self.gril_5_8 = QtGui.QGridLayout(self.gridLayoutWidget_73)
        self.gril_5_8.setObjectName(_fromUtf8("gril_5_8"))
        self.gridLayoutWidget_74 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_74.setGeometry(QtCore.QRect(390, 130, 51, 51))
        self.gridLayoutWidget_74.setObjectName(_fromUtf8("gridLayoutWidget_74"))
        self.gril_7_6 = QtGui.QGridLayout(self.gridLayoutWidget_74)
        self.gril_7_6.setObjectName(_fromUtf8("gril_7_6"))
        self.gridLayoutWidget_75 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_75.setGeometry(QtCore.QRect(510, 370, 51, 51))
        self.gridLayoutWidget_75.setObjectName(_fromUtf8("gridLayoutWidget_75"))
        self.gril_3_8 = QtGui.QGridLayout(self.gridLayoutWidget_75)
        self.gril_3_8.setObjectName(_fromUtf8("gril_3_8"))
        self.gridLayoutWidget_76 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_76.setGeometry(QtCore.QRect(450, 10, 51, 51))
        self.gridLayoutWidget_76.setObjectName(_fromUtf8("gridLayoutWidget_76"))
        self.gril_9_7 = QtGui.QGridLayout(self.gridLayoutWidget_76)
        self.gril_9_7.setObjectName(_fromUtf8("gril_9_7"))
        self.gridLayoutWidget_77 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_77.setGeometry(QtCore.QRect(510, 550, 51, 51))
        self.gridLayoutWidget_77.setObjectName(_fromUtf8("gridLayoutWidget_77"))
        self.gril_0_8 = QtGui.QGridLayout(self.gridLayoutWidget_77)
        self.gril_0_8.setObjectName(_fromUtf8("gril_0_8"))
        self.gridLayoutWidget_78 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_78.setGeometry(QtCore.QRect(510, 250, 51, 51))
        self.gridLayoutWidget_78.setObjectName(_fromUtf8("gridLayoutWidget_78"))
        self.gril_5_9 = QtGui.QGridLayout(self.gridLayoutWidget_78)
        self.gril_5_9.setObjectName(_fromUtf8("gril_5_9"))
        self.gridLayoutWidget_79 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_79.setGeometry(QtCore.QRect(450, 70, 51, 51))
        self.gridLayoutWidget_79.setObjectName(_fromUtf8("gridLayoutWidget_79"))
        self.gril_8_7 = QtGui.QGridLayout(self.gridLayoutWidget_79)
        self.gril_8_7.setObjectName(_fromUtf8("gril_8_7"))
        self.gridLayoutWidget_80 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_80.setGeometry(QtCore.QRect(450, 310, 51, 51))
        self.gridLayoutWidget_80.setObjectName(_fromUtf8("gridLayoutWidget_80"))
        self.gril_4_8 = QtGui.QGridLayout(self.gridLayoutWidget_80)
        self.gril_4_8.setObjectName(_fromUtf8("gril_4_8"))
        self.gridLayoutWidget_81 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_81.setGeometry(QtCore.QRect(510, 10, 51, 51))
        self.gridLayoutWidget_81.setObjectName(_fromUtf8("gridLayoutWidget_81"))
        self.gril_9_8 = QtGui.QGridLayout(self.gridLayoutWidget_81)
        self.gril_9_8.setObjectName(_fromUtf8("gril_9_8"))
        self.gridLayoutWidget_82 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_82.setGeometry(QtCore.QRect(450, 490, 51, 51))
        self.gridLayoutWidget_82.setObjectName(_fromUtf8("gridLayoutWidget_82"))
        self.gril_1_7 = QtGui.QGridLayout(self.gridLayoutWidget_82)
        self.gril_1_7.setObjectName(_fromUtf8("gril_1_7"))
        self.gridLayoutWidget_83 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_83.setGeometry(QtCore.QRect(510, 70, 51, 51))
        self.gridLayoutWidget_83.setObjectName(_fromUtf8("gridLayoutWidget_83"))
        self.gril_8_8 = QtGui.QGridLayout(self.gridLayoutWidget_83)
        self.gril_8_8.setObjectName(_fromUtf8("gril_8_8"))
        self.gridLayoutWidget_84 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_84.setGeometry(QtCore.QRect(390, 430, 51, 51))
        self.gridLayoutWidget_84.setObjectName(_fromUtf8("gridLayoutWidget_84"))
        self.gril_2_6 = QtGui.QGridLayout(self.gridLayoutWidget_84)
        self.gril_2_6.setObjectName(_fromUtf8("gril_2_6"))
        self.gridLayoutWidget_85 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_85.setGeometry(QtCore.QRect(390, 490, 51, 51))
        self.gridLayoutWidget_85.setObjectName(_fromUtf8("gridLayoutWidget_85"))
        self.gril_1_6 = QtGui.QGridLayout(self.gridLayoutWidget_85)
        self.gril_1_6.setObjectName(_fromUtf8("gril_1_6"))
        self.gridLayoutWidget_86 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_86.setGeometry(QtCore.QRect(390, 70, 51, 51))
        self.gridLayoutWidget_86.setObjectName(_fromUtf8("gridLayoutWidget_86"))
        self.gril_8_6 = QtGui.QGridLayout(self.gridLayoutWidget_86)
        self.gril_8_6.setObjectName(_fromUtf8("gril_8_6"))
        self.gridLayoutWidget_87 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_87.setGeometry(QtCore.QRect(510, 490, 51, 51))
        self.gridLayoutWidget_87.setObjectName(_fromUtf8("gridLayoutWidget_87"))
        self.gril_1_8 = QtGui.QGridLayout(self.gridLayoutWidget_87)
        self.gril_1_8.setObjectName(_fromUtf8("gril_1_8"))
        self.gridLayoutWidget_88 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_88.setGeometry(QtCore.QRect(390, 550, 51, 51))
        self.gridLayoutWidget_88.setObjectName(_fromUtf8("gridLayoutWidget_88"))
        self.gril_0_6 = QtGui.QGridLayout(self.gridLayoutWidget_88)
        self.gril_0_6.setObjectName(_fromUtf8("gril_0_6"))
        self.gridLayoutWidget_89 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_89.setGeometry(QtCore.QRect(510, 430, 51, 51))
        self.gridLayoutWidget_89.setObjectName(_fromUtf8("gridLayoutWidget_89"))
        self.gril_2_8 = QtGui.QGridLayout(self.gridLayoutWidget_89)
        self.gril_2_8.setObjectName(_fromUtf8("gril_2_8"))
        self.gridLayoutWidget_90 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_90.setGeometry(QtCore.QRect(390, 370, 51, 51))
        self.gridLayoutWidget_90.setObjectName(_fromUtf8("gridLayoutWidget_90"))
        self.gril_3_6 = QtGui.QGridLayout(self.gridLayoutWidget_90)
        self.gril_3_6.setObjectName(_fromUtf8("gril_3_6"))
        self.gridLayoutWidget_91 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_91.setGeometry(QtCore.QRect(570, 310, 51, 51))
        self.gridLayoutWidget_91.setObjectName(_fromUtf8("gridLayoutWidget_91"))
        self.gril_4_9 = QtGui.QGridLayout(self.gridLayoutWidget_91)
        self.gril_4_9.setObjectName(_fromUtf8("gril_4_9"))
        self.gridLayoutWidget_93 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_93.setGeometry(QtCore.QRect(570, 190, 51, 51))
        self.gridLayoutWidget_93.setObjectName(_fromUtf8("gridLayoutWidget_93"))
        self.gril_6_9 = QtGui.QGridLayout(self.gridLayoutWidget_93)
        self.gril_6_9.setObjectName(_fromUtf8("gril_6_9"))
        self.gridLayoutWidget_95 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_95.setGeometry(QtCore.QRect(570, 10, 51, 51))
        self.gridLayoutWidget_95.setObjectName(_fromUtf8("gridLayoutWidget_95"))
        self.gril_9_9 = QtGui.QGridLayout(self.gridLayoutWidget_95)
        self.gril_9_9.setObjectName(_fromUtf8("gril_9_9"))
        self.gridLayoutWidget_101 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_101.setGeometry(QtCore.QRect(570, 250, 51, 51))
        self.gridLayoutWidget_101.setObjectName(_fromUtf8("gridLayoutWidget_101"))
        self.gril_5_10 = QtGui.QGridLayout(self.gridLayoutWidget_101)
        self.gril_5_10.setObjectName(_fromUtf8("gril_5_10"))
        self.gridLayoutWidget_104 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_104.setGeometry(QtCore.QRect(570, 130, 51, 51))
        self.gridLayoutWidget_104.setObjectName(_fromUtf8("gridLayoutWidget_104"))
        self.gril_7_9 = QtGui.QGridLayout(self.gridLayoutWidget_104)
        self.gril_7_9.setObjectName(_fromUtf8("gril_7_9"))
        self.gridLayoutWidget_114 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_114.setGeometry(QtCore.QRect(570, 430, 51, 51))
        self.gridLayoutWidget_114.setObjectName(_fromUtf8("gridLayoutWidget_114"))
        self.gril_2_9 = QtGui.QGridLayout(self.gridLayoutWidget_114)
        self.gril_2_9.setObjectName(_fromUtf8("gril_2_9"))
        self.gridLayoutWidget_115 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_115.setGeometry(QtCore.QRect(570, 490, 51, 51))
        self.gridLayoutWidget_115.setObjectName(_fromUtf8("gridLayoutWidget_115"))
        self.gril_1_9 = QtGui.QGridLayout(self.gridLayoutWidget_115)
        self.gril_1_9.setObjectName(_fromUtf8("gril_1_9"))
        self.gridLayoutWidget_116 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_116.setGeometry(QtCore.QRect(570, 70, 51, 51))
        self.gridLayoutWidget_116.setObjectName(_fromUtf8("gridLayoutWidget_116"))
        self.gril_8_9 = QtGui.QGridLayout(self.gridLayoutWidget_116)
        self.gril_8_9.setObjectName(_fromUtf8("gril_8_9"))
        self.gridLayoutWidget_118 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_118.setGeometry(QtCore.QRect(570, 550, 51, 51))
        self.gridLayoutWidget_118.setObjectName(_fromUtf8("gridLayoutWidget_118"))
        self.gril_0_9 = QtGui.QGridLayout(self.gridLayoutWidget_118)
        self.gril_0_9.setObjectName(_fromUtf8("gril_0_9"))
        self.gridLayoutWidget_120 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_120.setGeometry(QtCore.QRect(570, 370, 51, 51))
        self.gridLayoutWidget_120.setObjectName(_fromUtf8("gridLayoutWidget_120"))
        self.gril_3_9 = QtGui.QGridLayout(self.gridLayoutWidget_120)
        self.gril_3_9.setObjectName(_fromUtf8("gril_3_9"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 55, 611, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 611, 31))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 170, 611, 31))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 230, 611, 31))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 290, 611, 31))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(20, 350, 611, 31))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(20, 410, 611, 31))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(20, 470, 611, 31))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(20, 530, 611, 31))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(60, 0, 51, 611))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(120, 0, 51, 611))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(180, 0, 51, 611))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(240, 0, 51, 611))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(300, 0, 51, 611))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(360, 0, 51, 611))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(420, 0, 51, 611))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.line_17 = QtGui.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(480, 0, 51, 611))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(540, 0, 51, 611))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(640, 190, 201, 291))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.AppStatus = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.AppStatus.setObjectName(_fromUtf8("AppStatus"))
        self.verticalLayout.addWidget(self.AppStatus)
        self.ShowAppStatus = QtGui.QTableView(self.verticalLayoutWidget_2)
        self.ShowAppStatus.setObjectName(_fromUtf8("ShowAppStatus"))
        self.verticalLayout.addWidget(self.ShowAppStatus)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(19, 620, 301, 131))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.GETMAP = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.GETMAP.setObjectName(_fromUtf8("GETMAP"))
        self.verticalLayout_8.addWidget(self.GETMAP)
        self.ShowGetMap = QtGui.QTextBrowser(self.verticalLayoutWidget_8)
        self.ShowGetMap.setObjectName(_fromUtf8("ShowGetMap"))
        self.verticalLayout_8.addWidget(self.ShowGetMap)
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(320, 620, 301, 131))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lastUpdate = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.lastUpdate.setObjectName(_fromUtf8("lastUpdate"))
        self.verticalLayout_9.addWidget(self.lastUpdate)
        self.showLastUpdate = QtGui.QTextBrowser(self.verticalLayoutWidget_9)
        self.showLastUpdate.setObjectName(_fromUtf8("showLastUpdate"))
        self.verticalLayout_9.addWidget(self.showLastUpdate)
        self.moveXY = QtGui.QPushButton(self.centralwidget)
        self.moveXY.setGeometry(QtCore.QRect(640, 600, 201, 27))
        self.moveXY.setObjectName(_fromUtf8("moveXY"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(640, 540, 201, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.x = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.x.setObjectName(_fromUtf8("x"))
        self.horizontalLayout_3.addWidget(self.x)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(640, 570, 201, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.y = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.y.setObjectName(_fromUtf8("y"))
        self.horizontalLayout_4.addWidget(self.y)
        self.blabla = QtGui.QLabel(self.centralwidget)
        self.blabla.setGeometry(QtCore.QRect(640, 500, 221, 21))
        self.blabla.setObjectName(_fromUtf8("blabla"))
        self.blabla_2 = QtGui.QLabel(self.centralwidget)
        self.blabla_2.setGeometry(QtCore.QRect(640, 520, 231, 16))
        self.blabla_2.setObjectName(_fromUtf8("blabla_2"))
        self.line_19 = QtGui.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(680, 490, 118, 3))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.PAUSE.setText(_translate("MainWindow", "PAUSE", None))
        self.PLAY.setText(_translate("MainWindow", "PLAY", None))
        self.QUIT.setText(_translate("MainWindow", "DISCONNECT", None))
        self.label_3.setText(_translate("MainWindow", "Name : ", None))
        self.PSEUDO.setText(_translate("MainWindow", "Valider le nouveau pseudo", None))
        self.moveUp.setText(_translate("MainWindow", "↑", None))
        self.moveLeft.setText(_translate("MainWindow", "←", None))
        self.moveRight.setText(_translate("MainWindow", "→", None))
        self.moveDown.setText(_translate("MainWindow", "↓", None))
        self.AppStatus.setText(_translate("MainWindow", "App status", None))
        self.GETMAP.setText(_translate("MainWindow", "Get robots position", None))
        self.lastUpdate.setText(_translate("MainWindow", "Last Update", None))
        self.moveXY.setText(_translate("MainWindow", "Valider le déplacement", None))
        self.label_4.setText(_translate("MainWindow", "X :", None))
        self.label_5.setText(_translate("MainWindow", "Y : ", None))
        self.blabla.setText(_translate("MainWindow", "Enter coordinates or use the", None))
        self.blabla_2.setText(_translate("MainWindow", "arrows to moove your robot", None))


